/**
 * HelloWorldDemo Sample: This sample demonstrates an agent that after creation
 * prints "Hello World!" message on the console and then terminates.
 * 
 * Running the sample:
 * 1. Press Ctrl-Shift-b to build the solution.
 * 2. Make sure WINAH is running. Load the agent by specifying the path of the 
 *    assembly generated by compilation of the solution and name of the agent
 *	  as "HelloWorldDemo.Agent1".
 * 
 * You should see "Hello World!" printed in the Output pane of WINAH.
 * 
 * Send comments and suggestions at siddharthuppal@yahoo.co.in.
 */

using System;
using EtherYatri;

namespace HelloWorldDemo
{
	/// <summary>
	/// This agent when loaded prints a Hello World message to the console
	/// and terminates.
	/// </summary>
	public class Agent1 : EtherYatri.Agent
	{
		// An agent does its main work in the Run method.
		public override void Run()
		{
			Console.WriteLine("Hello World!");
		}
	}
}
